# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ievnGYrlck47eX9y_iC2bumLngs0joc9
"""

print("Hello world!")

from google.colab import drive
drive.mount('/content/gdrive', force_remount=True)

import pandas as pd
from google.colab import drive

drive.mount('/content/gdrive', force_remount=True)
filepath = '/content/gdrive/My Drive/' + 'to_your_path/'

# 예시 : filepath = '/content/gdrive/My Drive/csv/'

df_data = pd.read_csv(filepath + 'BostonHousing.csv')
print(df_data.shape)